spring:
  application:
    name: cash-flow-visualization-tool
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=app_cashflow
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: app_cashflow
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/dev
    schemas: app_cashflow
